<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Replace_Receiver</name>
   <tag></tag>
   <elementGuidId>b713ac19-3f9e-42d8-9e3d-3cfb219aaee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ctl00_ctl05_fvlc_fvsvSearchReceipts_fvsvRecommendedTab_btnReplaceReceiver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
